// Generated by gencpp from file your_package_name/FindWall.msg
// DO NOT EDIT!


#ifndef YOUR_PACKAGE_NAME_MESSAGE_FINDWALL_H
#define YOUR_PACKAGE_NAME_MESSAGE_FINDWALL_H

#include <ros/service_traits.h>


#include <your_package_name/FindWallRequest.h>
#include <your_package_name/FindWallResponse.h>


namespace your_package_name
{

struct FindWall
{

typedef FindWallRequest Request;
typedef FindWallResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FindWall
} // namespace your_package_name


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::your_package_name::FindWall > {
  static const char* value()
  {
    return "66229cd821efb4126c80f35757f3c73e";
  }

  static const char* value(const ::your_package_name::FindWall&) { return value(); }
};

template<>
struct DataType< ::your_package_name::FindWall > {
  static const char* value()
  {
    return "your_package_name/FindWall";
  }

  static const char* value(const ::your_package_name::FindWall&) { return value(); }
};


// service_traits::MD5Sum< ::your_package_name::FindWallRequest> should match
// service_traits::MD5Sum< ::your_package_name::FindWall >
template<>
struct MD5Sum< ::your_package_name::FindWallRequest>
{
  static const char* value()
  {
    return MD5Sum< ::your_package_name::FindWall >::value();
  }
  static const char* value(const ::your_package_name::FindWallRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::your_package_name::FindWallRequest> should match
// service_traits::DataType< ::your_package_name::FindWall >
template<>
struct DataType< ::your_package_name::FindWallRequest>
{
  static const char* value()
  {
    return DataType< ::your_package_name::FindWall >::value();
  }
  static const char* value(const ::your_package_name::FindWallRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::your_package_name::FindWallResponse> should match
// service_traits::MD5Sum< ::your_package_name::FindWall >
template<>
struct MD5Sum< ::your_package_name::FindWallResponse>
{
  static const char* value()
  {
    return MD5Sum< ::your_package_name::FindWall >::value();
  }
  static const char* value(const ::your_package_name::FindWallResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::your_package_name::FindWallResponse> should match
// service_traits::DataType< ::your_package_name::FindWall >
template<>
struct DataType< ::your_package_name::FindWallResponse>
{
  static const char* value()
  {
    return DataType< ::your_package_name::FindWall >::value();
  }
  static const char* value(const ::your_package_name::FindWallResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YOUR_PACKAGE_NAME_MESSAGE_FINDWALL_H
