// Generated by gencpp from file wall_follower_pkg/FindWall.msg
// DO NOT EDIT!


#ifndef WALL_FOLLOWER_PKG_MESSAGE_FINDWALL_H
#define WALL_FOLLOWER_PKG_MESSAGE_FINDWALL_H

#include <ros/service_traits.h>


#include <wall_follower_pkg/FindWallRequest.h>
#include <wall_follower_pkg/FindWallResponse.h>


namespace wall_follower_pkg
{

struct FindWall
{

typedef FindWallRequest Request;
typedef FindWallResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FindWall
} // namespace wall_follower_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wall_follower_pkg::FindWall > {
  static const char* value()
  {
    return "66229cd821efb4126c80f35757f3c73e";
  }

  static const char* value(const ::wall_follower_pkg::FindWall&) { return value(); }
};

template<>
struct DataType< ::wall_follower_pkg::FindWall > {
  static const char* value()
  {
    return "wall_follower_pkg/FindWall";
  }

  static const char* value(const ::wall_follower_pkg::FindWall&) { return value(); }
};


// service_traits::MD5Sum< ::wall_follower_pkg::FindWallRequest> should match
// service_traits::MD5Sum< ::wall_follower_pkg::FindWall >
template<>
struct MD5Sum< ::wall_follower_pkg::FindWallRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wall_follower_pkg::FindWall >::value();
  }
  static const char* value(const ::wall_follower_pkg::FindWallRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wall_follower_pkg::FindWallRequest> should match
// service_traits::DataType< ::wall_follower_pkg::FindWall >
template<>
struct DataType< ::wall_follower_pkg::FindWallRequest>
{
  static const char* value()
  {
    return DataType< ::wall_follower_pkg::FindWall >::value();
  }
  static const char* value(const ::wall_follower_pkg::FindWallRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wall_follower_pkg::FindWallResponse> should match
// service_traits::MD5Sum< ::wall_follower_pkg::FindWall >
template<>
struct MD5Sum< ::wall_follower_pkg::FindWallResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wall_follower_pkg::FindWall >::value();
  }
  static const char* value(const ::wall_follower_pkg::FindWallResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wall_follower_pkg::FindWallResponse> should match
// service_traits::DataType< ::wall_follower_pkg::FindWall >
template<>
struct DataType< ::wall_follower_pkg::FindWallResponse>
{
  static const char* value()
  {
    return DataType< ::wall_follower_pkg::FindWall >::value();
  }
  static const char* value(const ::wall_follower_pkg::FindWallResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WALL_FOLLOWER_PKG_MESSAGE_FINDWALL_H
